In [ ]:
import pandas as pd
import numpy as np

In [12]:
df1 = pd.read_csv('raw/prices/1f69c0ba-db0a-4b7c-a9ac-41fd0f777eed.csv')
df2 = pd.read_csv('raw/prices/12cfb125-8fa9-4401-8b0f-9d928544b721.csv')
df3 = pd.read_csv('raw/prices/4a75119f-d4e4-46f2-a461-360e14b3f50c.csv')
df4 = pd.read_csv('raw/prices/79b3b772-7875-4358-91fb-e7025ce7e406.csv')

In [79]:
test = pd.read_csv('processed/lmp_2018-21.csv')

In [64]:
df = pd.concat([df1, df2, df3, df4])

In [65]:
df

,interval_start_local,interval_start_utc,interval_end_local,interval_end_utc,location,lmp
0,2010-11-30T00:00:00-06:00,2010-11-30 06:00:00+00:00,2010-11-30T01:00:00-06:00,2010-11-30 07:00:00+00:00,PYR_PYRON1,15.242353
1,2010-11-30T01:00:00-06:00,2010-11-30 07:00:00+00:00,2010-11-30T02:00:00-06:00,2010-11-30 08:00:00+00:00,PYR_PYRON1,4.209231
2,2010-11-30T02:00:00-06:00,2010-11-30 08:00:00+00:00,2010-11-30T03:00:00-06:00,2010-11-30 09:00:00+00:00,PYR_PYRON1,-1.615000
3,2010-11-30T03:00:00-06:00,2010-11-30 09:00:00+00:00,2010-11-30T04:00:00-06:00,2010-11-30 10:00:00+00:00,PYR_PYRON1,6.802500
4,2010-11-30T04:00:00-06:00,2010-11-30 10:00:00+00:00,2010-11-30T05:00:00-06:00,2010-11-30 11:00:00+00:00,PYR_PYRON1,17.145833
...,...,...,...,...,...,...
14610,2025-08-31T19:00:00-05:00,2025-09-01 00:00:00+00:00,2025-08-31T20:00:00-05:00,2025-09-01 01:00:00+00:00,PYR_PYRON1,30.504167
14611,2025-08-31T20:00:00-05:00,2025-09-01 01:00:00+00:00,2025-08-31T21:00:00-05:00,2025-09-01 02:00:00+00:00,PYR_PYRON1,34.626667
14612,2025-08-31T21:00:00-05:00,2025-09-01 02:00:00+00:00,2025-08-31T22:00:00-05:00,2025-09-01 03:00:00+00:00,PYR_PYRON1,38.806923
14613,2025-08-31T22:00:00-05:00,2025-09-01 03:00:00+00:00,2025-08-31T23:00:00-05:00,2025-09-01 04:00:00+00:00,PYR_PYRON1,39.975000
14614,2025-08-31T23:00:00-05:00,2025-09-01 04:00:00+00:00,2025-09-01T00:00:00-05:00,2025-09-01 05:00:00+00:00,PYR_PYRON1,39.647500

In [66]:
df['datetime'] = pd.to_datetime(df['interval_start_local'])

/var/folders/ld/ry50f5bs3tzgqgpbq7z2_6pw0000gn/T/ipykernel_8434/4213472726.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df['datetime'] = pd.to_datetime(df['interval_start_local'])

In [67]:
df['datetime'] = df['datetime'].astype(str)

In [70]:
df['datetime'] = df['datetime'].str.replace('-06:00', '')
df['datetime'] = df['datetime'].str.replace('-05:00', '')

In [77]:
lmps = df[['datetime', 'lmp']]
lmps

                  datetime        lmp
0      2010-11-30 00:00:00  15.242353
1      2010-11-30 01:00:00   4.209231
2      2010-11-30 02:00:00  -1.615000
3      2010-11-30 03:00:00   6.802500
4      2010-11-30 04:00:00  17.145833
...                    ...        ...
14610  2025-08-31 19:00:00  30.504167
14611  2025-08-31 20:00:00  34.626667
14612  2025-08-31 21:00:00  38.806923
14613  2025-08-31 22:00:00  39.975000
14614  2025-08-31 23:00:00  39.647500

[129328 rows x 2 columns]

In [78]:
lmps.to_csv('processed/lmp_2010-25.csv', index=False)